#!/usr/bin/env python

import pico, rospy
from std_msgs.msg import Float32

def publisher():
	print("Avvio il publisher...")
	pub = rospy.Publisher('battery_lvl', Float32, queue_size=1)
	rospy.init_node("publisher", anonymous=True)
	rate = rospy.Rate(1)
	while not rospy.is_shutdown():
		v = pico.get_bat_voltage()
		rospy.loginfo(v)
		pub.publish(v)
		rate.sleep()

if __name__ == "__main__":
	try:
		publisher()
	except rospy.ROSInterruptException:
		pass
